-- Generated by GmodSoundGen

-- File: D:\Downloads\important_stuff_v2\Tools\GmodSoundGen_0519\weapon_pi_papa320.all.lua
-- Total length: 125

-- Sound: 16
sound.Add({
	name = "weap_papa320_fire_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/papa320/weap_papa320_fire_plr_01.ogg",
		}
})
sound.Add({
	name = "weap_papa320_fire_first",
	channel = CHAN_WEAPON,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/papa320/weap_papa320_fire_first_plr_01.ogg",
		}
})
sound.Add({
	name = "weap_papa320_fire_disconnector",
	channel = CHAN_WEAPON,

	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/papa320/weap_papa320_disconnector_plr_01.ogg",
		}
})
-- Sound: 48
sound.Add({
	name = "weap_papa320_sup_plr",
	channel = CHAN_WEAPON,
	level = 140,
	volume = 1,
	pitch = {100,100},
	sound = {
		"weapons/golf21/weap_golf21_supp_plr_01.ogg",
		}
})
-- Sound: 66
sound.Add({
	name = "weap_pi_papa320_ads_down",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/weap_pi_papa320_ads_down.ogg",
		}
})
-- Sound: 67
sound.Add({
	name = "weap_pi_papa320_ads_up",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/weap_pi_papa320_ads_up.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_drop_01",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_drop_down.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_raise_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_raise_up.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_raise_first_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_raise_first_start.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_raise_first_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_raise_first_open_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_raise_first_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_raise_first_close_01.ogg",
		}
})
-- Sound: 68
sound.Add({
	name = "wfoly_plr_pi_papa320_raise_first_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_raise_first_end.ogg",
		}
})
-- Sound: 69
sound.Add({
	name = "wfoly_plr_pi_papa320_inspect_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_pi_papa320_inspect_01.ogg",
		}
})
-- Sound: 70
sound.Add({
	name = "wfoly_plr_pi_papa320_inspect_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_pi_papa320_inspect_02.ogg",
		}
})
-- Sound: 71
sound.Add({
	name = "wfoly_plr_pi_papa320_inspect_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_pi_papa320_inspect_03.ogg",
		}
})
-- Sound: 72
sound.Add({
	name = "wfoly_plr_pi_papa320_inspect_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_pi_papa320_inspect_04.ogg",
		}
})
-- Sound: 73
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_start.ogg",
		}
})
-- Sound: 74
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_magout_01.ogg",
		}
})
-- Sound: 75
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_wiggle.ogg",
		}
})
-- Sound: 76
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_magin_v2_01.ogg",
		}
})
-- Sound: 77
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_045",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_magin_v2_02.ogg",
		}
})
-- Sound: 78
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_05",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_end.ogg",
		}
})
-- Sound: 79
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_start.ogg",
		}
})
-- Sound: 80
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_magout_01.ogg",
		}
})
-- Sound: 81
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_regrip.ogg",
		}
})
-- Sound: 82
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_arm.ogg",
		}
})
-- Sound: 83
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_magin_v2_01.ogg",
		}
})
-- Sound: 84
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_055",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_magin_v2_02.ogg",
		}
})
-- Sound: 85
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_end.ogg",
		}
})
-- Sound: 86
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_charge_01.ogg",
		}
})
-- Sound: 87
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_start.ogg",
		}
})
-- Sound: 88
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_magout_01.ogg",
		}
})
-- Sound: 89
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_arm.ogg",
		}
})
-- Sound: 90
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_magin_01.ogg",
		}
})
-- Sound: 91
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_charge_01.ogg",
		}
})
-- Sound: 92
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_06",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_end.ogg",
		}
})
-- Sound: 93
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_start.ogg",
		}
})
-- Sound: 94
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 95
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_arm.ogg",
		}
})
-- Sound: 96
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_magin_01.ogg",
		}
})
-- Sound: 97
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_end.ogg",
		}
})
-- Sound: 98
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_fast_xmag_06",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_fast_xmag_charge_01.ogg",
		}
})
-- Sound: 99
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_01",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_start.ogg",
		}
})
-- Sound: 100
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_02",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_magout_01.ogg",
		}
})
-- Sound: 101
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_03",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_regrip.ogg",
		}
})
-- Sound: 102
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_04",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_arm.ogg",
		}
})
-- Sound: 103
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_05",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 104
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_055",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 105
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_06",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_charge_01.ogg",
		}
})
-- Sound: 106
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_empty_xmag_07",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_empty_xmag_end.ogg",
		}
})
-- Sound: 107
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_start.ogg",
		}
})
-- Sound: 108
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_magout_01.ogg",
		}
})
-- Sound: 109
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_arm.ogg",
		}
})
-- Sound: 110
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_magin_01.ogg",
		}
})
-- Sound: 111
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_end.ogg",
		}
})
-- Sound: 112
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_xmag_01",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_xmag_start.ogg",
		}
})
-- Sound: 113
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_xmag_02",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_xmag_magout_01.ogg",
		}
})
-- Sound: 114
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_xmag_03",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_xmag_arm.ogg",
		}
})
-- Sound: 115
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_xmag_04",
	channel = CHAN_WPNFOLEY + 1,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_xmag_magin_01.ogg",
		}
})
-- Sound: 116
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_fast_xmag_05",
	channel = CHAN_WPNFOLEY + 2,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_fast_xmag_end.ogg",
		}
})
-- Sound: 117
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_01",
	channel = CHAN_WPNFOLEY + 3,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_start.ogg",
		}
})
-- Sound: 118
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_02",
	channel = CHAN_WPNFOLEY + 4,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_arm.ogg",
		}
})
-- Sound: 119
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_03",
	channel = CHAN_WPNFOLEY + 5,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_magout_01.ogg",
		}
})
-- Sound: 120
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_04",
	channel = CHAN_WPNFOLEY + 6,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_thumb.ogg",
		}
})
-- Sound: 121
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_05",
	channel = CHAN_WPNFOLEY + 7,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_magin_v2_01.ogg",
		}
})
-- Sound: 122
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_055",
	channel = CHAN_WPNFOLEY + 8,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_magin_v2_02.ogg",
		}
})
-- Sound: 123
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_06",
	channel = CHAN_WPNFOLEY + 9,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_wiggle.ogg",
		}
})
-- Sound: 124
sound.Add({
	name = "wfoly_plr_pi_papa320_reload_xmag_07",
	channel = CHAN_WPNFOLEY + 10,
	
	volume = 1,
	pitch = {100,100},
	sound = {
		"reloads/iw8_papa320/wfoly_plr_pi_papa320_reload_xmag_end.ogg",
		}
})
